<?php

namespace AppBundle\Repository;

/**
 * CustomerTargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerTargetRepository extends \Doctrine\ORM\EntityRepository
{
}
