AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        detail:
            type: string
            length: '50'
            unique: true
        parentId:
            type: integer
    lifecycleCallbacks: {  }
